name: Everton Quadros
description: Software Developer
meta_description: "Everton Quadros personal website."

markdown: kramdown
highlighter: rouge
logo: '/assets/images/profile2.jpeg'
paginate: 15
baseurl: /
url: 'https://eqdrs.github.io/'
domain_name: 'https://eqdrs.github.io/'
google_analytics: 'UA-146875310-1'
gems: [jekyll-paginate]
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

# Details for the RSS feed generator
url:            'https://eqdrs.github.io'
author:         'Everton Quadros'
